PUT http://localhost:3003/api/blogs/62a6fc27bd76c7847f35c4ef
Content-Type: application/json

{
    "title": "Päivitystesti",
    "author": "Tommi Testaaja",
    "url": "http://404notfoun.de",
    "likes": -666
}